# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.100-preview.4.20258.7'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- task: DotNetCoreCLI@2
  displayName: 'Pack Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'Push Nuget Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'my feed key'